remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Otus. Unity Game Developer Professional. 2023]
description: [Homeworks collection]

show_downloads: ["true"]
